<#
.SYNOPSIS
  Provision the production payments API service on the VPS.

.DESCRIPTION
  This script installs only infrastructure wiring: /etc/qflash-payments.env,
  backend asset keys, qflash-payments.service, and the Nginx /api proxy.
  It never generates or prints payOS/admin secrets. Provide those in a private
  env file such as .env.production.local.
#>
[CmdletBinding()]
param(
  [string]$EnvPath       = ".env.production.local",
  [string]$AssetKeysPath = "server\data\payment-asset-keys.local.json",
  [string]$KeyPath       = $(if ($env:QFLASH_DEPLOY_KEY) { $env:QFLASH_DEPLOY_KEY } else { "C:\Users\XuanNguyen\Downloads\VPS.pem" }),
  [string]$HostTarget    = $(if ($env:QFLASH_DEPLOY_HOST) { $env:QFLASH_DEPLOY_HOST } else { "ubuntu@43.134.51.214" }),
  [string]$RemoteRoot    = $(if ($env:QFLASH_DEPLOY_ROOT) { $env:QFLASH_DEPLOY_ROOT } else { "/var/www/unlock.choimaytau.com/app" }),
  [string]$PublicUrl     = $(if ($env:QFLASH_DEPLOY_PUBLIC_URL) { $env:QFLASH_DEPLOY_PUBLIC_URL } else { "https://unlock.choimaytau.com" }),
  [string]$RemoteDataDir = "/var/lib/qflash-payments",
  [string]$KnownHosts    = $(if ($env:QFLASH_DEPLOY_KNOWN_HOSTS) { $env:QFLASH_DEPLOY_KNOWN_HOSTS } else { Join-Path $env:USERPROFILE ".ssh\known_hosts_qflash" }),
  [switch]$CheckOnly
)

$ErrorActionPreference = "Stop"

Set-Location -LiteralPath "C:\Users\XuanNguyen\Documents\Q-Flash-Web"

function Read-EnvFile {
  param([Parameter(Mandatory)][string]$Path)

  $map = [ordered]@{}
  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match '^\s*$' -or $line -match '^\s*#') {
      continue
    }
    if ($line -notmatch '^([^=]+)=(.*)$') {
      throw "Invalid env line in $Path. Expected KEY=value format."
    }
    $name = $Matches[1].Trim()
    $value = $Matches[2]
    if ($name -match '\s') {
      throw "Invalid env key '$name' in $Path."
    }
    $map[$name] = $value
  }
  return $map
}

function Require-SecretValue {
  param(
    [Parameter(Mandatory)][hashtable]$Map,
    [Parameter(Mandatory)][string]$Name
  )

  if (-not $Map.Contains($Name) -or [string]::IsNullOrWhiteSpace([string]$Map[$Name])) {
    throw "$Name is required in $EnvPath."
  }
}

function Write-EnvFile {
  param(
    [Parameter(Mandatory)][hashtable]$Map,
    [Parameter(Mandatory)][string]$Path
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by scripts/provision-payments-vps.ps1. Do not commit.")
  foreach ($key in $Map.Keys) {
    $lines.Add("$key=$($Map[$key])")
  }
  [System.IO.File]::WriteAllText(
    $Path,
    (($lines -join [Environment]::NewLine) + [Environment]::NewLine),
    (New-Object System.Text.UTF8Encoding($false))
  )
}

function Invoke-Ssh {
  param([Parameter(Mandatory)][string]$Command)
  $oldErrorActionPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $output = & ssh @sshOpts -o BatchMode=yes $HostTarget $Command 2>&1
    $exitCode = $LASTEXITCODE
  } finally {
    $ErrorActionPreference = $oldErrorActionPreference
  }
  if ($exitCode -ne 0) {
    $text = ($output | Out-String).Trim()
    throw "SSH command failed with exit code $exitCode. $text"
  }
  return $output
}

function Invoke-Scp {
  param([Parameter(Mandatory)][string[]]$Arguments)

  $oldErrorActionPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    & scp @sshOpts -q @Arguments
    $exitCode = $LASTEXITCODE
  } finally {
    $ErrorActionPreference = $oldErrorActionPreference
  }
  if ($exitCode -ne 0) {
    throw "SCP failed with exit code $exitCode."
  }
}

if (-not (Test-Path -LiteralPath $EnvPath)) {
  throw "Private env file not found at $EnvPath. Create it with real payOS/admin values outside git."
}
if (-not (Test-Path -LiteralPath $AssetKeysPath)) {
  throw "Backend asset key file not found at $AssetKeysPath. Run npm.cmd run build:assets or point -AssetKeysPath at the private key file."
}
if (-not (Test-Path -LiteralPath $KeyPath)) {
  throw "SSH key not found at $KeyPath."
}

$envMap = Read-EnvFile -Path $EnvPath
foreach ($name in @("PAYMENTS_ADMIN_TOKEN", "PAYOS_CLIENT_ID", "PAYOS_API_KEY", "PAYOS_CHECKSUM_KEY")) {
  Require-SecretValue -Map $envMap -Name $name
}

$publicBaseUrl = $PublicUrl.TrimEnd("/")
$remoteAssetKeysPath = "$($RemoteDataDir.TrimEnd('/'))/payment-asset-keys.local.json"
$remoteDbPath = "$($RemoteDataDir.TrimEnd('/'))/payments.db"

$envMap["PAYMENTS_PORT"] = "8787"
$envMap["PAYMENTS_DATABASE_PATH"] = $remoteDbPath
$envMap["PAYMENTS_PUBLIC_BASE_URL"] = $publicBaseUrl
$envMap["PAYMENTS_PROVIDER"] = "payos"
$envMap["PAYMENTS_ASSET_KEYS_PATH"] = $remoteAssetKeysPath
$envMap["PAYOS_RETURN_URL"] = "$publicBaseUrl/payment/return"
$envMap["PAYOS_CANCEL_URL"] = "$publicBaseUrl/payment/cancel"
$envMap["PAYOS_WEBHOOK_URL"] = "$publicBaseUrl/api/payments/webhook/payos"

if ([string]$envMap["PAYMENTS_ALLOW_MOCK_IN_PRODUCTION"]) {
  throw "Remove PAYMENTS_ALLOW_MOCK_IN_PRODUCTION from $EnvPath before provisioning production."
}

$knownHostsDir = Split-Path -Parent $KnownHosts
if ($knownHostsDir -and -not (Test-Path -LiteralPath $knownHostsDir)) {
  New-Item -ItemType Directory -Path $knownHostsDir -Force | Out-Null
}
if (-not (Test-Path -LiteralPath $KnownHosts)) {
  New-Item -ItemType File -Path $KnownHosts -Force | Out-Null
}

$sshOpts = @(
  "-o", "UserKnownHostsFile=$KnownHosts",
  "-o", "StrictHostKeyChecking=accept-new",
  "-o", "ConnectTimeout=10",
  "-o", "ServerAliveInterval=15",
  "-i", $KeyPath
)

$remoteProbe = @'
set -e
service=0
env=0
nginx=0
node=0
current_backend=0
if command -v node >/dev/null 2>&1; then node=1; fi
if systemctl list-unit-files qflash-payments.service --no-legend 2>/dev/null | grep -q qflash-payments; then service=1; fi
if sudo test -s /etc/qflash-payments.env; then env=1; fi
if sudo nginx -T 2>/dev/null | grep -Eq 'location[[:space:]]+/api/?[[:space:]]*\{'; then nginx=1; fi
if test -d '__REMOTE_ROOT__/current/server/dist'; then current_backend=1; fi
printf 'node=%s service=%s env=%s nginx=%s current_backend=%s\n' "$node" "$service" "$env" "$nginx" "$current_backend"
'@.Replace("__REMOTE_ROOT__", $RemoteRoot)

$readiness = Invoke-Ssh -Command $remoteProbe
Write-Host ($readiness | Out-String).Trim()

if ($CheckOnly) {
  Write-Host "CheckOnly complete. No files were uploaded and no remote configuration was changed." -ForegroundColor Cyan
  exit 0
}

$stagedEnv = Join-Path $env:TEMP "qflash-payments.env"
$remoteScript = Join-Path $env:TEMP "qflash-provision-payments.sh"
try {
  Write-EnvFile -Map $envMap -Path $stagedEnv

  $bash = @'
set -euo pipefail

remote_root="$1"
remote_data_dir="$2"
remote_asset_keys_path="$3"
port="$4"

if ! command -v node >/dev/null 2>&1; then
  echo "node is required on the VPS." >&2
  exit 1
fi

sudo install -d -m 750 -o www-data -g www-data "$remote_data_dir"
sudo install -d -m 750 -o www-data -g www-data "$(dirname "$remote_asset_keys_path")"
sudo install -m 640 -o root -g www-data /tmp/qflash-payments.env "$remote_data_dir/qflash-payments.env.uploaded"
sudo install -m 640 -o root -g www-data /tmp/qflash-payment-asset-keys.local.json "$remote_asset_keys_path"
sudo mv "$remote_data_dir/qflash-payments.env.uploaded" /etc/qflash-payments.env
sudo rm -f /tmp/qflash-payments.env /tmp/qflash-payment-asset-keys.local.json

sudo tee /etc/systemd/system/qflash-payments.service >/dev/null <<UNIT
[Unit]
Description=Q Flash Web payments API
After=network.target

[Service]
Type=simple
WorkingDirectory=$remote_root/current
Environment=NODE_ENV=production
EnvironmentFile=/etc/qflash-payments.env
ExecStart=/usr/bin/node server/dist/index.js
Restart=on-failure
RestartSec=3
User=www-data
Group=www-data

[Install]
WantedBy=multi-user.target
UNIT

nginx_file="$(sudo grep -RslE 'server_name[[:space:]].*unlock\.choimaytau\.com' /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/conf.d 2>/dev/null | head -n 1 || true)"
if [ -z "$nginx_file" ]; then
  echo "Could not find an Nginx server block for unlock.choimaytau.com." >&2
  exit 1
fi

if ! sudo grep -Eq 'location[[:space:]]+/api/?[[:space:]]*\{' "$nginx_file"; then
  tmp="$(sudo mktemp)"
  sudo cp "$nginx_file" "$nginx_file.qflash-backup-$(date +%Y%m%d%H%M%S)"
  sudo python3 - "$nginx_file" "$tmp" "$port" <<'PY'
import re
import sys

src, dst, port = sys.argv[1:4]
with open(src, encoding="utf-8") as handle:
    text = handle.read()

if re.search(r"location\s+/api/?\s*\{", text):
    with open(dst, "w", encoding="utf-8") as handle:
        handle.write(text)
    raise SystemExit(0)

block = f"""    location /api/ {{
        proxy_pass http://127.0.0.1:{port}/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

"""

match = re.search(r"\n\s*location\s+/\s*\{", text)
if not match:
    raise SystemExit("Could not find a location / block to insert before.")

text = text[: match.start() + 1] + block + text[match.start() + 1 :]
with open(dst, "w", encoding="utf-8") as handle:
    handle.write(text)
PY
  sudo install -m 644 "$tmp" "$nginx_file"
  sudo rm -f "$tmp"
fi

if [ ! -d "$remote_root/current/server/dist" ]; then
  echo "Current release does not include server/dist. Run deploy.ps1 after provisioning." >&2
  exit 1
fi

sudo nginx -t
sudo systemctl daemon-reload
sudo systemctl enable qflash-payments.service
sudo systemctl restart qflash-payments.service
sudo systemctl reload nginx
sudo systemctl --no-pager --full status qflash-payments.service | sed -n '1,8p'
'@
  [System.IO.File]::WriteAllText($remoteScript, $bash, (New-Object System.Text.UTF8Encoding($false)))

  Invoke-Scp -Arguments @($stagedEnv, "${HostTarget}:/tmp/qflash-payments.env")
  Invoke-Scp -Arguments @($AssetKeysPath, "${HostTarget}:/tmp/qflash-payment-asset-keys.local.json")
  Invoke-Scp -Arguments @($remoteScript, "${HostTarget}:/tmp/qflash-provision-payments.sh")

  $remoteCommand = "bash /tmp/qflash-provision-payments.sh '$RemoteRoot' '$RemoteDataDir' '$remoteAssetKeysPath' '8787'; rm -f /tmp/qflash-provision-payments.sh"
  Invoke-Ssh -Command $remoteCommand

  $healthUrl = "$publicBaseUrl/api/health"
  $health = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -Headers @{ "Cache-Control" = "no-cache" }
  if ($health.StatusCode -ne 200 -or [string]$health.Headers["Content-Type"] -notmatch "application/json") {
    throw "Provisioning completed, but public health check failed: status=$($health.StatusCode), content-type=$($health.Headers["Content-Type"])."
  }
  $healthBody = $health.Content | ConvertFrom-Json
  if ($healthBody.ok -ne $true) {
    throw "Provisioning completed, but public health JSON did not include ok=true."
  }

  Write-Host "Payments backend provisioned and public /api/health is healthy." -ForegroundColor Green
} finally {
  Remove-Item -LiteralPath $stagedEnv -Force -ErrorAction SilentlyContinue
  Remove-Item -LiteralPath $remoteScript -Force -ErrorAction SilentlyContinue
}
