[CmdletBinding()]
param(
  [ValidateSet("local", "production")]
  [string]$Mode = "local",
  [string]$EnvPath = ".env.local"
)

$ErrorActionPreference = "Stop"

function Read-Required([string]$Prompt) {
  $value = Read-Host $Prompt
  if ([string]::IsNullOrWhiteSpace($value)) {
    throw "$Prompt is required."
  }
  return $value.Trim()
}

function New-Token {
  $bytes = [byte[]]::new(32)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  return [Convert]::ToHexString($bytes).ToLowerInvariant()
}

function Set-EnvValue([System.Collections.IDictionary]$Map, [string]$Name, [string]$Value) {
  $Map[$Name] = $Value
}

$clientId = Read-Required "PAYOS_CLIENT_ID"
$apiKey = Read-Required "PAYOS_API_KEY"
$checksumKey = Read-Required "PAYOS_CHECKSUM_KEY"
$adminTokenInput = Read-Host "PAYMENTS_ADMIN_TOKEN (leave empty to generate)"
$adminToken = if ([string]::IsNullOrWhiteSpace($adminTokenInput)) { New-Token } else { $adminTokenInput.Trim() }

$publicBaseUrl = if ($Mode -eq "production") { "https://unlock.choimaytau.com" } else { "http://localhost:5173" }
$apiBaseUrl = if ($Mode -eq "production") { "https://unlock.choimaytau.com" } else { "http://localhost:8787" }

$paymentValues = [ordered]@{}
Set-EnvValue $paymentValues "PAYMENTS_PORT" "8787"
Set-EnvValue $paymentValues "PAYMENTS_DATABASE_PATH" "server/data/payments.db"
Set-EnvValue $paymentValues "PAYMENTS_PUBLIC_BASE_URL" $publicBaseUrl
Set-EnvValue $paymentValues "PAYMENTS_PROVIDER" "payos"
Set-EnvValue $paymentValues "PAYMENTS_ADMIN_TOKEN" $adminToken
Set-EnvValue $paymentValues "PAYMENTS_ASSET_KEYS_PATH" "server/data/payment-asset-keys.local.json"
Set-EnvValue $paymentValues "PAYOS_CLIENT_ID" $clientId
Set-EnvValue $paymentValues "PAYOS_API_KEY" $apiKey
Set-EnvValue $paymentValues "PAYOS_CHECKSUM_KEY" $checksumKey
Set-EnvValue $paymentValues "PAYOS_RETURN_URL" "$publicBaseUrl/payment/return"
Set-EnvValue $paymentValues "PAYOS_CANCEL_URL" "$publicBaseUrl/payment/cancel"
Set-EnvValue $paymentValues "PAYOS_WEBHOOK_URL" "$apiBaseUrl/api/payments/webhook/payos"

$lines = New-Object System.Collections.Generic.List[string]
if (Test-Path -LiteralPath $EnvPath) {
  $lines.Add("# Existing non-payment variables are preserved below when possible.")
  foreach ($line in Get-Content -LiteralPath $EnvPath) {
    if ($line -match '^(PAYMENTS_|PAYOS_)') {
      continue
    }
    $lines.Add($line)
  }
  $lines.Add("")
}

$lines.Add("# payOS payments - generated by scripts/setup-payos-local.ps1")
foreach ($entry in $paymentValues.GetEnumerator()) {
  $lines.Add("$($entry.Key)=$($entry.Value)")
}

Set-Content -LiteralPath $EnvPath -Value $lines -Encoding UTF8
New-Item -ItemType Directory -Path "server/data" -Force | Out-Null
if (-not (Test-Path -LiteralPath "server/data/payment-asset-keys.local.json")) {
  Set-Content -LiteralPath "server/data/payment-asset-keys.local.json" -Value "{}" -Encoding UTF8
}

Write-Host "Wrote $EnvPath with payOS payments config." -ForegroundColor Green
Write-Host "Admin token is set in $EnvPath. Keep that file private." -ForegroundColor Yellow
Write-Host "Start backend with: powershell -ExecutionPolicy Bypass -File scripts/start-payos-local.ps1" -ForegroundColor Cyan
